### ISSUE TITLE
Floating IP's Silently Fail

### ISSUE THREAD

**Issue by cbaenziger** [cloudbau/vagrant-openstack-plugin#100]
I'm having some issues with the instructions suggested in #99. I receive the following when trying to set the below (for reference, our [clouds](http://github.com/bloomberg/chef-bcpc/) are still using nova-network which does not expose a network endpoint for Fog to talk to).

Error:
````
/home/ubuntu/.vagrant.d/gems/gems/fog-1.25.0/lib/fog/openstack/core.rb:143:in `authenticate_v2': Could not find service network.  Have cloudformation, compute, ec2, identity, image, orchestration, volume (Fog::Errors::NotFound)
````

Vagrantfile:
````
require 'vagrant-openstack-plugin'
Vagrant.configure(2) do |config|
  config.vm.define :claytest do |claytest|
    hostname="clay-test"
    claytest.ssh.private_key_path = "~/.ssh/vagrant-test.pem"
    claytest.vm.box = "dummy"
    claytest.vm.hostname = hostname
    claytest.vm.provider :openstack do |os|
      os.server_name = hostname
      # os.floating_ip = '1.2.3.4'
      os.networks = ['network1']
      [...]
    end
    config.vm.network 'private_network', ip: '1.2.3.4'
end
````

Formally, `os.floating_ip = "1.2.3.4"` used to work for floating IP's but I see that is no longer working since 0.8.0 (it does not assign the IP but does not trigger a configuration file error either). Also, `os.floating_ip = :auto` now fails to work too. There's no mention of the floating IP with `vagrant --debug up --provider=openstack` in this case.

**Comment by joelanford** [comment]
I also ran into this issue.  I think it's a simple fix.  It looks like a copy/paste error in config.rb, where @floating_ip is set to nil if @floating_ip_pool is equal to UNSET_VALUE.  I posted a pull request with the one-line fix.

**Comment by ehaselwanter** [comment]
merged. re-open if still an issue
