### ISSUE TITLE
`vagrant up` not taking advantage of already-allocated-but-unmapped floating IP address

### ISSUE THREAD

**Issue by lastmikoi** [cloudbau/vagrant-openstack-plugin#112]
Hello and thanks for this awesome plugin.

However, I'm currently running into an issue when I use this plugin to create a new vm :
Indeed, I am working under a specific Openstack project, with a limited tenant which has a limited(15) quota of floating IP addresses; And whenever I `vagrant up` a new instance it maps a new floating IP to said instance, using the `nova` pool (as configured).

But when I reach my quota of allocated floating IP addresses, I am unable to create this vm:
```
/home/username/.vagrant.d/gems/gems/excon-0.45.3/lib/excon/middlewares/expects.rb:6:in `response_call': Expected([200, 202]) <=> Actual(403 Forbidden) (Excon::Errors::Forbidden)
excon.error.response
  :body          => "{\"forbidden\": {\"message\": \"IP allocation over quota in pool nova.\", \"code\": 403}}"
  :headers       => {
    "Content-Length"       => "81"
    "Content-Type"         => "application/json; charset=UTF-8"
    "Date"                 => "Wed, 17 Jun 2015 15:15:58 GMT"
    "X-Compute-Request-Id" => "REDACTED"
  }
```

Which is *to be expected*. But since I have 12 unmapped (and thus ready to use) floating IP addresses in my project, I expected the provider to use those unmapped IP addresses before even trying to allocate another one.

Here are my provider-specific settings:

```ruby
            vm_config.vm.provider :openstack do |os, override|
                override.ssh.private_key_path = "~/.ssh/id_rsa"
                os.username = "#{ENV['OS_USERNAME']}"
                os.api_key = "#{ENV['OS_PASSWORD']}"
                os.endpoint = "#{ENV['OS_AUTH_URL']}/tokens"
                os.tenant = "#{ENV['OS_TENANT_NAME']}"

                os.server_name = "#{full_project_name}-#{env}-#{host[:name]}"
                os.flavor = /m1.small/
                os.image = /Ubuntu-Trusty-Server-14.04-LTS-x86_64/
                os.ssh_username = "ubuntu"
                os.security_groups = ['default']
                os.keypair_name = "REDACTED"
                if host[:network]
                    os.floating_ip = host[:network]
                else
                    os.floating_ip = :auto
                    os.floating_ip_pool = "nova"
                end
            end
```
*(In this specific case host[:network] is not defined)*

Did I overlooked something in the documentation or is this behavior really a *bug* ?

**Comment by Chealion** [comment]
I would say this is a bug in the documentation, or the behaviour needs to be changed to attempt to use already available floating IPs (which assumes that one of those IPs is actually safe to take).

**Comment by lastmikoi** [comment]
@Chealion I see. 

I am not sufficiently fluent in Ruby to submit a patch myself, but I think my issue could be solved in two different ways :
* Making sure to take unused IP before trying to allocate one from the pool
* **OR** Making sure `vagrant destroy` releases the IP into the pool (which is not the case)

This is an annoying issue for me as I have to regularly release floating IP addresses into the pool, from the dashboard, in order to avoid exceeding my quota.

**Comment by maxx** [comment]
Just a note that I've solved this.  In my patch, instead of using

os.floating_ip = :auto

we can use

os.floating_ip = :associate_unassigned

and it will grab the next unassigned IP from the pool specified in os.floating_ip_pool.

Pull request coming shortly. .

**Comment by lastmikoi** [comment]
@maxx Nice to hear !

Will this `:associate_unassigned` flag fallback to the `:auto` behavior if there is no unassigned IP addresses left ?

**Comment by maxx** [comment]
No, but that's a good idea. I'll try to get that in too.

**Comment by maxx** [comment]
It's a good idea, but on second thought, I may not do that because it doesn't fit my particular use case.  In my case, I want to grab an assigned IP from a given pool, and only that pool. I don't want to assign any IP's out of that pool.  If there's none available in that pool, I would want to fail.  This could be relevant if the IPs in a pool are associated with a set of rules or a network configuration.  This is really built around that use case.

**Comment by maxx** [comment]
https://github.com/cloudbau/vagrant-openstack-plugin/pull/118

**Comment by ehaselwanter** [comment]
merged, re-open if not fixed for you
