### ISSUE TITLE
Support of config.ssh.password

### ISSUE THREAD

**Issue by sbourlon** [cloudbau/vagrant-openstack-plugin#116]
Hi everyone,

Does the plugin support `config.ssh.password` instead of using `config.ssh.private_key_path`?

Thanks!

**Comment by ehaselwanter** [comment]
would you mind to clarify? you want to set the ssh password in the config file?

**Comment by sbourlon** [comment]
Thanks Edmund for the reply.

`you want to set the ssh password in the config file?`

That's correct. I would be glad to use something like `config.ssh.password` (https://docs.vagrantup.com/v2/vagrantfile/ssh_settings.html) with the vagrant-openstack-plugin in order to open the ssh session with a password. I tried `config.ssh.password` with no success. Maybe is there another way to open the ssh session with a password?
