### ISSUE TITLE
Vagrant up hangs sometimes

### ISSUE THREAD

**Issue by seanguo** [cloudbau/vagrant-openstack-plugin#119]
I used this plugin to interact with our openstack server. But it will hang sometimes.   This hang happens when invoking the command `vagrant up driver --provider=openstack --no-provision` .
 
And all the plugins installed is as following:

vagrant plugin list
* omnibus (4.0.0)
* vagrant-aws (0.5.0)
  - Version Constraint: 0.5.0
* vagrant-awsinfo (0.0.8)
* vagrant-berkshelf (4.1.0)
* vagrant-openstack-plugin (0.12.0)
* vagrant-share (1.1.5, system)

Attached a thread dump, a sample vagrant file and the vagrant debug logs.  I omitted some of the sensitive data in the files.

[driver.up.txt](https://github.com/mitchellh/vagrant/files/78297/driver.up.txt)
[Vagrantfile.txt](https://github.com/mitchellh/vagrant/files/78299/Vagrantfile.txt)
[thread_dump.txt](https://github.com/mitchellh/vagrant/files/78298/thread_dump.txt)

Please advice. Thanks.

**Comment by maxx** [comment]
@seanguo can this be reproduced consistently? I would say if it's working at least some of the time, it's more likely going to be an OpenStack issue. Older OpenStack versions classically have issues around nova api calls hanging on build requests.

Are you able to query the server state via nova API or the Horizon web interface?  Is it stuck building?  I would check the nova api logs on the other end ..

**Comment by seanguo** [comment]
@maxx  No, it hangs sometimes. Thanks for you advice. I'll check for the nova logs. One thing to point out is that when the hang happens we can still manually ssh to that hanged machine.

**Comment by maxx** [comment]
interesting.. that leads me to believe it's not a nova issue then. do the
hangs always happen when trying to ssh? maybe take a tcpdump when the
plugin is trying to connect to determine if the ssh attempt is actually
happening ..

The only other thing I could think of is the IP is failing to associate..
but if you can still reach the host from the same machine, then that's not
the case..

**Comment by seanguo** [comment]
OK. Finally I figured it out, this is also related to the "config.ssh.pty" setting. It need to be set to false(by default) and the VM need to disable/comment out "requiretty" inside the "/etc/sudoers". This also fixes the issue that vagrant can not get the provision logs until the provision is done.
