### ISSUE TITLE
Free floating IP addresses only searched for within current project

### ISSUE THREAD

**Issue by dme26** [cloudbau/vagrant-openstack-plugin#82]
`vagrant up --provider=openstack` was failing to allocate floating IP addresses, reporting that there were none free. However the Horizon dashboard reported plenty of free floating IP addresses. (I am an admin of a particular tenant on an OpenStack instance that I am using, but am not an admin of the overall OpenStack system itself.)

The plugin seems to be searching for unassociated IP addresses within the current project: e.g. running `nova floating-ip-list` needs to show entries with "Fixed Ip" column indicating "None" for the plugin to associate them successfully.  However, even if this list has no such addresses, and the plugin fails, I can still successfully associate new floating IP addresses to instances by using the Horizon dashboard.

As a workaround, if I associate the number of floating addresses that I need and then dissociate them, through Horizon, they will become accessible to the plugin.

I suspect that this relates to what's mentioned on http://docs.openstack.org/user-guide/content/floating_ip_disassociate.html regarding the difference between `floating-ip-disassociate` and `floating-ip-delete`, where in the latter case, the "IP address is returned to the pool of IP addresses that is available for all projects." In my context—I'm not sure how unusual it is—it seems that I can't see the addresses in this pool, but I can still use Horizon to associate floating IP addresses from it. Ideally the plugin would be able to request (:auto) floating IPs in the same way that the Horizon dashboard does.

**Comment by ehaselwanter** [comment]
Hi, would you mind updating this issue. #118 should fix this. re-open if still an issue
