### ISSUE TITLE
Undefined method if "disks" config item is omitted (on 0.10)

### ISSUE THREAD

**Issue by arbrandes** [cloudbau/vagrant-openstack-plugin#92]
Just installed 0.10, and this is what I get when trying to build my stack:

```
/home/arbrandes/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.10.0/lib/vagrant-openstack-plugin/action/create_server.rb:146:in `block in call': undefined method `empty?' for nil:NilClass (NoMethodError)
```

If I add an "os.disks = []"  line to the Vagrantfile, things just work.  Looks like it's just a bad check on line 146 of create_server.rb.

**Comment by ehaselwanter** [comment]
merged, re-open if still an issue
